<a href="https://colab.research.google.com/github/SabhyaGrover/Data-Science-UCS655/blob/main/AI_app_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 3-Numpy**

1. Create an array of 10 fives

In [ ]:
import numpy as np
np.full((1,10),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

2. Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

3. Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

4. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5. Use NumPy to generate an array of 25 random numbers sampled from a standard normal
distribution

In [ ]:
np.random.standard_normal(25)
# (mean=0, stdev=1)

array([-0.22606681, -0.42620221, -0.54066255, -0.14121559, -0.9660026 ,
       -0.46894576, -0.39424154,  0.07796017, -1.4365044 , -0.73894775,
       -0.93327904, -0.82548412, -0.87767286,  1.64835529, -1.54232824,
       -0.99779473, -0.09336834, -0.71054602, -1.49483369, -0.40359924,
       -0.29836182, -0.55991873,  1.27444076,  0.30439434,  1.44947261])

6. Create the following array:

array([0. , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
0.99, 1. ])

In [ ]:
np.arange(start=0, stop=1.01, step=0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

7. Create an array of 20 linearly spaced points between 0 and 1

In [ ]:
np.linspace(start=0, stop=1, num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

8. Generate the following matrix, mat,

array([[ 1, 2, 3, 4, 5],
[ 6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20],
[21, 22, 23, 24, 25]])

and extract the following using the indexing and slicing:

array([[12, 13, 14, 15],
[17, 18, 19, 20],
[22, 23, 24, 25]])

array([[ 2],
[ 7],
[12]])

Get the sum of all the values in mat
Get the sum of all the rows and columns in mat

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat[2:5][...,1:]
# Get the sum of all elements in Matrix
print(np.sum(mat))
# Get Column Wise sum ( Axis = 0 )
print(np.sum(mat,axis=0))
# Get Row Wise sum ( Axis = 1 )
print(np.sum(mat,axis=1))

325
[55 60 65 70 75]
[ 15  40  65  90 115]




---

